# Configuration file to generate test-ui via kickoff
# kickoff -a test-dashboard.yml -f ~/topics/react-redux-ui-archetype/ -d test-test-dashboard
package_name: test-react-app
package_description: A react frontend application
author_full_name: Test Author
author_email: testauthor@gmail.com
author_github_account: testauthor
