# Configuration file to generate test-ui via kickoff
# kickoff -a test-react-redux-app.yml -f ~/topics/react-redux-app/ -d test-react-redux-app
package_name: test-react-redux-app
package_description: A react frontend application
author_full_name: Test Author
author_email: testauthor@gmail.com
author_github_account: testauthor
